---
language: ruby

dist: trusty
sudo: false

before_install:
  - rvm get head
  - gem install bundler
  - export CXX="g++-4.8"

addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-4.8

rvm:
  - 2.1.10
  - 2.2.4
  - 2.3.1
  - ruby-head
  - rbx
  - jruby
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
    # rack 2.0 requires Ruby version >= 2.2.2
    - gemfile: gemfiles/rack_2_0_x.gemfile
      rvm: 2.1.10
  fast_finish: true

before_install: gem install bundler

script:
  - bundle exec rspec

gemfile:
  - gemfiles/rack_1_3_x.gemfile
  - gemfiles/rack_1_6_x.gemfile
  - gemfiles/rack_2_0_x.gemfile

addons:
  code_climate:
    repo_token: e2838e3d1990c8374751d6267300d349f20d019dbcf38daffafc58bd2ab765cc
