---
language: ruby

dist: trusty
sudo: false

before_install:
  - rvm get head
  - gem install bundler
  - export CXX="g++-4.8"

addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-4.8

rvm:
  - 2.1.10
  - 2.2.4
  - 2.3.1
  - ruby-head
  - rbx
  - jruby-9.1.0.0
  - jruby-9.1.3.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx

before_install: gem install bundler

script:
  - bundle exec rspec

gemfile:
  - gemfiles/rack_1_3_x.gemfile
  - gemfiles/rack_1_6_x.gemfile
  - gemfiles/rack_2_0_x.gemfile
